### ISSUE TITLE
Succession de <c level="recordgrp"> ?

### ISSUE THREAD

**Issue by ElsaVK** [sbiay/DM-EAD-TNAH-2022#10]
Bonjour bonjour :)

J'ai une question à laquelle je n'ai pas trouvé de réponse dans les issues précédentes donc je la pose ici.

Dans ce cas là : 
![question](https://user-images.githubusercontent.com/92538363/176546462-840252d5-6f68-4d76-a06f-2b69762ac179.png)

Je me pose la question de comment encoder la sous-partie Ministère des Affaires Culturelles qui comporte plusieurs sous-parties.

Au début j'avais procédé en faisant ainsi, c'est à dire en ne faisant pas de distinction et en mettant tout dans une même balise <item>
![recordgrp](https://user-images.githubusercontent.com/92538363/176546669-ddedad6b-d0af-4424-9c21-e11710d63aee.png)

Mais finalement je me dis que peut-être il faut que j'encode à un niveau un peu plus fin ? En ajoutant à la suite un <c level="recordgrp"> du même <unitid> type="identifiant" 20110282/4 que le précédent, ce qui donnerait ceci : 
![ministere](https://user-images.githubusercontent.com/92538363/176547050-221af3de-e6ac-4132-8f89-3532db122e68.png)

Procédure que je devrais répéter dès que le scénario se répète, par exemple dans la même première capture d'écran avec le Ministère de l'Equipement qui comporte lui aussi plusieurs parties..

Voilà, j'espère avoir été claire ! Et merci à vous pour tout votre travail :)
Elsa

**Comment by sbiay** [comment]
Salut Elsa,

Zoé a justement trouvé une idée pour ce genre de problème. Je parle sous son contrôle, mais je crois que ta solution est parfaite. Juste une mini-chose, ce sera un `<c level="subgrp">`.

En fait nous envisageons que tous les éléments de  liste des `scopcontent` soient encodés dans des `c`, mais c'est encore en débat, et si c'est l'option que nous adoptons, nous l'appliquerons partout avec XSLT et non à la main. Cela ne t'empêche pas d'appliquer ta solution dans ce cas spécifique dès à présent si Zoé valide.

Bonne journée

**Comment by zcappe** [comment]
La solution me paraît bonne aussi, effectivement le `<c level="subgrp">` sera plus adapté dans ce cas-là.
Bonne journée !
