### ISSUE TITLE
Note de bas de page

### ISSUE THREAD

**Issue by baudbaudy** [sbiay/DM-EAD-TNAH-2022#14]
Beaucoup de groupe y sont confrontés mais il n'y a pas encore eu de réponse ou suggestion. Comment est-il préférable de baliser les notes de bas de page?

**Comment by zcappe** [comment]
Nous cherchons une solution que nous appliquerons à tous les cas une fois que les productions des groupes seront ajoutées à l'encodage, vous pouvez donc les ignorer.
