### ISSUE TITLE
Harmonisation fichiers EAC-CPF et EAD

### ISSUE THREAD

**Issue by SjdkC** [sbiay/DM-EAD-TNAH-2022#21]
Bonjour !

Le fichier EAC-CPF est terminé et une PR a été proposée. Quelques harmonisations doivent être effectuées entre ce fichier et le fichier EAD :

**I/ Compléter la relation entre la notice producteur et l'instrument de recherche**

1) Dans la notice d'autorité :
```
<resourceRelation xmlns:xlink="http://www.w3.org/1999/xlink" resourceRelationType="creatorOf" xlink:href="?" xlink:type="simple">
    <relationEntry localType="archival">?</relationEntry>
</resourceRelation>
```

compléter l'attribut "xlink:href" avec l’identifiant provisoire de l’instrument de recherche
compléter l’élément “relationEntry” avec le titre de l’instrument de recherche (reprendre l’élément “titlestmt” de l’instrument de recherche)

2) Dans l’instrument de recherche, ajouter dans archdesc/did/ :

```
<origination>
    <persname authfilenumber="FRAN_NP_005412">Île-de-France. Conservation régionale des monuments historiques (1948-...)</persname>
</origination>
```
On a modifié la forme autorisée du nom du producteur : il faut donc vérifier que l’ancienne forme est bien remplacée partout.

**II/ Harmoniser le bioghist dans l'IR en EAD, car quelques points semblent poser problème :**
    
“Elles ont pris le nom de conservations régionales des monuments historiques en 1979.” : il semblerait que la filiation entre les deux institutions soit plus compliquée que ça, donc il vaudrait peut-être mieux dire que la CRMH a repris leurs missions.

“(CRMH)” : à enlever.

N'hésitez pas à nous dire si vous avez des questions, ou si vous voulez qu'on modifie nous mêmes le fichier EAC-CPF lorsque vous aurez décidé d'un identifiant provisoire et d'un titre pour l'instrument de recherche !

**Comment by vicpsl** [comment]
Merci,
plusieurs sources indiquent que les Conservations régionales des bâtiments de France sont devenues les Conservations régionales des Monuments Historiques donc c'est confus, y compris l'IR d'origine "Les premières conservations régionales des bâtiments de France ont été créées à la Libération.
Elles ont pris le nom de conservations régionales des monuments historiques en 1979."
Les fonds recouvrent l'activité au sein de plusieurs producteur successifs CRBF devenue CRMH, puis SNT. Certains dossiers inclus font référence au Service départemental de l’architecture et du patrimoine (1986) (20110282/7).

Donc effectivement, il convient sans doute de ne pas référencer une <toDate> pour ces activités.

**Comment by SjdkC** [comment]
L'harmonisation ayant été faite, je ferme l'issue.
