### ISSUE TITLE
origination: comment renseigner le producteur du fond

### ISSUE THREAD

**Issue by sbiay** [sbiay/DM-EAD-TNAH-2022#3]
En passant par la salle des inventaires virtuels, on trouve cette notice : [FRAN_NP_005412](https://www.siv.archives-nationales.culture.gouv.fr/siv/NP/FRAN_NP_005412).

Le corrigé de la notice Léon Blum reprend ce type d'identifiant de producteur créé par les AN : `<persname authfilenumber="FRAN_NP_050200">Blum, Léon (1872-1950)</persname>`

En reprenant la forme autorisée, nous aurions donc :
```xml
<origination>
    <corpname authfilenumber="FRAN_NP_005412">Conservation régionale des monuments historiques d'Île-de-France</corpname>
</origination>
```

**Comment by zcappe** [comment]
Cela me semble bon, nous pouvons l'ajouter à l'encodage
