### ISSUE TITLE
c level="file" (dossier): comment articuler ce niveau à la description par boîte ?

### ISSUE THREAD

**Issue by sbiay** [sbiay/DM-EAD-TNAH-2022#4]
Zoé :
> S'il n'y a pas de dossier correspondant à un édifice particulier, on passera directement à la description par item.
> Si la boîte correspond à un seul édifice, on se contente d'un composant de ce type. Possibilité d'utiliser un level="subgroup" pour un sous-groupe de documents ? ou est-ce que subgroup est en lien avec recordgroup ?
> S'il y a plusieurs édifices dans une boîte, on créera de nouveaux <c level="file"> dans ledit composant afin de créer des sous-dossiers (il n'y pas d'attribut @type qui y corresponde.)

Je ne suis pas sûr que la boîte doive être un élément de notre hiérarchique, ce n'est qu'une unité de conditionnement… L'encodage suivant est en tout cas conforme à la DTD :

```xml
<c level="file">
    <did>
        <unitid type="identifiant">20110282/15-20110282/21</unitid>
        <unittitle>Archives nationales</unittitle>
        <unitdate normal=""><!--compléter--></unitdate>
    </did>
    <c level="item">
        <did>
            <unitid type="identifiant">20110282/15</unitid>
            <unittitle>Hôtel de Rohan </unittitle>
            <unitdate normal=""><!--compléter--></unitdate>
        </did>
    </c>
    <c level="item">
        <did>
            <unitid type="identifiant">20110282/15</unitid>
            <unittitle>Hôtel de Soubise </unittitle>
            <unitdate normal=""><!--compléter--></unitdate>
        </did>
    </c>
</c>
```

**Comment by zcappe** [comment]
Je voyais plutôt le problème au nivau des édifices, qui sont des dossiers dans les Archives nationales et qui comprennent des items : les Archives nationales ont-elles donc le niveau de groupe de documents et les deux Hôtels seraient chacun un sous-groupe ? Est-ce qu'on conserve un @level="file" pour tous les types de dossiers/groupes de dossiers ou est-ce qu'il faudrait utiliser un autre @level ?


```xml
<c level="file">
    <did>
        <unitid type="identifiant">20110282/15-20110282/21</unitid>
        <unittitle>Archives nationales</unittitle>
        <unitdate normal=""><!--compléter--></unitdate>
    </did>
    <c level="file">
        <did>
            <unitid type="identifiant">20110282/15</unitid>
            <unittitle>Hôtel de Rohan </unittitle>
            <unitdate normal=""><!--compléter--></unitdate>
        </did>
        <c level="item">
           <did>
                <unittitle>Dorure de la grille principale</unittitle>
               <unitdate normal="1982">1982</unitdate>
           </did>
         </c>
    </c>
    <c level="file">
        <did>
            <unitid type="identifiant">20110282/15</unitid>
            <unittitle>Hôtel de Soubise </unittitle>
            <unitdate normal=""><!--compléter--></unitdate>
        </did>
        <!-- ... -->
    </c>
</c>
```

**Comment by sbiay** [comment]
Même si certains "file" ont des "item" et d'autres pas, la nature des "file" ne me semble pas beaucoup changer : ce sont des domaines (c'est le mot qui me semble le plus englobant), comprenant parfois plusieurs sites. C'est vrai que parfois il s'agit d'institutions (Archives nationales, Ministère de la Culture) et parfois de monuments accueillant plusieurs institutions (Palais-Royal, Hôtel national des Invalides) - mais qui nous dit qu'il n'existe pas aussi une entité administrative propre pour chacun de ces monuments (qui seraient alors des institutions en tant que telles, englobant d'autres institutions), c'est le plus probable. D'où l'idée de les définir globalement comme des domaines pour éviter de devoir redéfinir chaque "file"…

**Comment by sbiay** [comment]
En résumé, je suivrais de près la hiérarchie de l'IR afin de respecter la hiérarchie du fonds.

**Comment by sbiay** [comment]
Après se pose la question de comment encoder les informations du type "Dorure de la grille principale (1982)." etc

Ce ne sont même pas des pièces (sans doute qu'il y a plusieurs pièces pour chaque intervention : des plans, des devis, des factures, des lettres). On pourrait dire que toutes ces informations restent sous forme de bloc et vont dans un élément `abstract`. 

Qu'en pensez-vous ?

**Comment by zcappe** [comment]
Effectivement, les dossiers dans les dossiers ne sont pas envisageables.

La solution que tu proposes me paraît intéressante, on pourrait peut-être utiliser `scopecontent` plutôt que `abstract` ? Si je comprends bien le premier sert à décrire le contenu des unités documentaires, tandis que le second sert plutôt à donner des informations sur leur classement ou le producteur.

**Comment by sbiay** [comment]
Très bonne idée : scopecontent avec une liste comme sous élément !

**Comment by zcappe** [comment]
La liste serait parfaite ! Je change donc la documentation

**Comment by zcappe** [comment]
Et dans les cas sans divisions en dossiers (édifices dans les lieux), cela donnerait ça:
```XML
<c level="subseries">
    <did>
        <unitid type="identifiant"><!--compléter--></unitid>
        <unittitle>Paris</unittitle>
        <unitdate normal=""><!--compléter--></unitdate>
    </did>
    <c level="recordgrp">
        <did>
            <unitid>20110282/1</unittitle>
            <unitdate normal=""><!--compléter--></unitdate>
        </did>
        <scopecontent>
            <list>
                <item>Arc de triomphe (1968-1987).</item>
                <item>Archives nationales (1968-1987)</item>
                <!--compléter la liste-->
            </list>
        </scopecontent>
    </c>
    <c level="recordgrp">
        <did>
            <unitid>20110282/2</unittitle>
            <unitdate normal=""><!--compléter--></unitdate>
        </did>
        <scopecontent>
            <list>
                <item>Conservatoire national supérieur de musique</item>
                <item>Conservatoire national des arts et métiers</item>
                <!--compléter la liste-->
            </list>
        </scopecontent>
    </c>
</c
```

**Comment by sbiay** [comment]
Oui, pour la série organique "programmation" je suis d'accord.

Mais dans la série Dossier de travaux, on est ok que Arc de Triomphe serait un file ?
