### ISSUE TITLE
Qu'est-ce qu'on veut faire du <unitid> pour le <did> d'un <c level="series"> ?

### ISSUE THREAD

**Issue by kat-kel** [sbiay/DM-EAD-TNAH-2022#6]
L'Identification et description (`<did>`) d'un Composant niveau "series" (`<c level="series">`) veut décrire l'une des séries organiques de cet instrument de recherche. Il y en a deux nommé dans le plan de classement :

> **Plan de classement**
>
> Conservation régionale des monuments historiques d'Ile-de-France : 
> programmation et conduite de travaux sur des édifices publics
> 
> **Art. 1-13 : programmation. 1956-1991**
> 
> **Art. 14-74 : conduite de travaux. 1962-1993**

Est-ce qu'on veut prendre comme `<unitid>` la phrase "Art. ??-??" qui précède le nom d'une série (ci-dessus) ? Les consignes de devoir nous disent de ne pas enconder le plan de classement. Mais je pense qu'il serait utilie d'au moins prendre les dates qui succèdent le nom de série dans le plan de classement pour les mettre dans le `<unitdate>`.

En exemple : 
https://github.com/sbiay/DM-EAD-TNAH-2022/blob/110498f48ef3c502cb40a5621239e2436f08f53e/encodage.xml#L140-L144

Est-ce que cet exemple ci-dessus, d'une description de l'une des séries organiques du plan de classement, vous semble bien ? Ou devrait-on supprimer l'élément `<unitid>` ?

**Comment by kat-kel** [comment]
En outre, le nom de série n'est pas toujours le même. Le deuxième composant s'appelle *conduite de travaux* dans le plan de classement. Mais dans l'instrument de recherche, il s'appelle *II. Dossiers de travaux*. Pour être clair, on veut ignorer le nom écrit dans le plan de classement et faire référence uniquement au nom utilisé plus tard dans l'instrument de recherche, c'est ça ?

**Comment by zcappe** [comment]
Le `<unitid>` sert à décrire les identifiants, je pense donc qu'il serait bien de préciser les cotes exactes:

```XML
<did> 
     <unitid type="identifiant">20110282/1-20110282/13</unitid> 
     <unittitle>I-Programmation</unittitle> 
     <unitdate normal="1956/1991">1956-1991</unitdate> 
 </did> 
```

**Comment by zcappe** [comment]
Les deux noms de la deuxième série faisant référence à la meme chose, je pense qu'on peut choisir l'un ou l'autre... Pour éviter de faire une erreur, il serait peut-être mieux de conserver les noms indiqués dans le document d'origine : le choix des deux noms distincts est peut-être fait pour une raison particulière.
