### ISSUE TITLE
Composant fichier (<c level="file">) composé de plusieurs fichiers

### ISSUE THREAD

**Issue by kat-kel** [sbiay/DM-EAD-TNAH-2022#7]
Ce composant fichier (`<c level="file">`) décrit plusieurs fichiers (Art. 15 - 21). Le premier fichier, no. 15, se compose de plusieurs groupes de registres, tel que le *Hôtel de Rohan*.

https://github.com/sbiay/DM-EAD-TNAH-2022/blob/96e1c04c90709e24124caf593dca00c2df87fd50/encodage.xml#L247-L256

Ensuite, le deuxième fichier dans ce composant "fichier" est no. 16, qui a aussi plusieurs groupes de registres tel que *Hôtels d'Assy, de Breteuil et de Fontenay*.

https://github.com/sbiay/DM-EAD-TNAH-2022/blob/96e1c04c90709e24124caf593dca00c2df87fd50/encodage.xml#L275-L281

J'aimerais bien enregistrer le propre identifiant du fichier parent dans lequel se situe chaque groupe de registres. En exemple :
```
<c level="file">
    <did>
        <unitid type="identifiant">20110282/15</unitid>
        <unittitle></unittitle>
        <unitdate normal="1982/1990">1982-1990</unitdate>
    </did>
    <c level="recordgrp">
        <did>
            <unittitle>Hôtel de Rohan</unittitle>
```
Du coup, je me demande s'il y a un souci autour de la classification de la rubrique "Archives nationales", qui est actuellement classé comme un composant fichier (`<c level="file">`). Est-ce qu'il y a un meilleur moyen de décrire le niveau d'information qui est la rubrique "Archives nationales" ?

**Comment by zcappe** [comment]
La situation a normalement été expliquée dans la documentation que nous avons rédigée (voir le fichier documentation.md) et la discussion sur le sujet peut être trouvée dans une des issues fermées

**Comment by sbiay** [comment]
Chère Kelly, 

Je me demande s'il n'y a pas un malentendu de type linguistique. Selon Isad-G, *file* ne signifie pas "fichier" mais "dossier".

La définition donnée par [isad_g_2f.pdf](https://github.com/florenceclavaud/cours-ENC2408/blob/master/ISADG/isad_g_2f.pdf) est la suivante :

> **Dossier**. Ensemble de documents regroupés, soit par le producteur pour son usage courant, soit dans le processus du classement d'archives, parce qu'ils concernent un même sujet ou une même affaire. Le dossier est ordinairement l'unité de base à l'intérieur d'une série organique.

**Comment by kat-kel** [comment]
Bonjour,
Merci, Sébastien, pour la clarification. Je me demande toujours s'il faut avoir qu'un seul dossier dans un composant "file", et si un dossier n'est pas un article dans le fonds (ex. 201102082/15). Ou est-ce qu'un composant dossier peut avoir plusieurs articles.

**Comment by sbiay** [comment]
Article ne fait pas non plus partie des niveaux de description, comme le montre le schéma [isad_g_2f.pdf](https://github.com/florenceclavaud/cours-ENC2408/blob/master/ISADG/isad_g_2f.pdf) (**p. 38**).

Je pense que l'on peut dire que les cotes ou boîtes correspondent à des articles et qu'en effet un dossier peut se composer de plusieurs articles, ou bien qu'un article peut contenir plusieurs petits dossiers.

**Comment by kat-kel** [comment]
D'accord. Merci encore. Je vais fermer l'issue.
