### ISSUE TITLE
<date> ou <unitdate> dans <item> ?

### ISSUE THREAD

**Issue by zcappe** [sbiay/DM-EAD-TNAH-2022#9]
Les éléments (`<item>`) contenus dans des listes à l'intérieur des`<scopecontent>` ont chacun une date. 
Le composant qui contient cette date décrit déjà leur intervalle de dates avec un `<unitdate @normal="...">`.

Selon vous est-il plus judicieux d'ajouter, pour chacun des items, un élément `<unitdate>` (qui requiert l'utilisation de l'attribut `@normal`) ou un élément `<date>` (sans attribut) ?

`<unitdate>` est défini ainsi dans l'EAD Tag Library: description de l'unité documentaire
`date` est défini ainsi : élément générique qui contient une mention de mois, de jour ou d'année sous n’importe quelle forme

Le premier est donc plus précis puisqu'il s'agit bien d'une unité documentaire, cependant nous utilisons le `<scopecontent>` et non des éléments `<c>` pour chaque item : nous décrivons donc l'unité documentaire qui a déjà elle-même un `<unitdate>` qui la décrit.
Un `<date>`, avec un attribut `@normal` serait moins précis, mais pourrait permettre de distinguer les dates de l'unité documentaire englobante (composant) de ses unités documentaires internes (items).

Qu'en pensez-vous ?

Un exemple de ma proposition : 

```XML
<c level="subseries">
    <did>
        <unittitle>Paris</unittitle>
    </did>
    <c level="file">
        <did>
            <unitid type="identifiant">20110282/14</unitid>
            <unittitle>Arc de Triomphe </unittitle>
            <unitdate normal=""><!--compléter--></unitdate>
        </did>
        <scopecontent>
            <list>
                <item>Crypte Kléber, comptoir de vente et rénovation des circulations (<date normal="1972">1972</date>).</item>
                <item>Plaque commémorative pour les militaires morts en Afrique du Nord (<date normal="1972">1972</date>).</item>
                <!--Compléter la liste-->
            </list>
        </scopecontent>
    </c>
</c>
```

**Comment by sbiay** [comment]
Entièrement d'accord ! Et merci pour la regex. Sauf autre avis, je vais fermer l'issue.

**Comment by zcappe** [comment]
Les éléments `date` et `unidate` ne sont en fait pas autorisés dans les `item`. Nous ne pouvons donc pas préciser la date des items.
